# Generated by Django 5.2.8 on 2025-11-29 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('estimated_hours', models.PositiveIntegerField(help_text='Estimated hours to complete the task', validators=[django.core.validators.MinValueValidator(1)])),
                ('importance', models.PositiveIntegerField(help_text='Importance rating from 1 (low) to 10 (high)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('dependencies', models.JSONField(blank=True, default=list, help_text='List of task IDs that this task depends on')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
